version: '3.7'

services:
  web:
    build:
      dockerfile: Dockerfile
      target: dev
      context: .
      args:
        - PHP_VERSION
        - WORDPRESS_VERSION
        - WOOCOMMERCE_VERSION
    depends_on:
      - db
    ports:
      - 8888:80
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: examplepass
      PHP_IDE_CONFIG: serverName=docker
      USER_ID: ${USER_ID:-1000}
      GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - wp-content:/app/src/wp-content
      - .:/app/src/wp-content/plugins/storekeeper-woocommerce-b2c:ro

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: somerootpassword
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8881:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: somerootpassword

volumes:
  db:
  wp-content:
