version: '3.7'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: docker
      args:
        PHP_VERSION: $PHP_VERSION
        THECODINGMACHINE_VERSION: $THECODINGMACHINE_VERSION
        WORDPRESS_VERSION: $WORDPRESS_VERSION
        WOOCOMMERCE_VERSION: $WOOCOMMERCE_VERSION
        STOREFRONT_VERSION: $STOREFRONT_VERSION
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8888:80
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: examplepass
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - .:/var/www/html/storekeeper-for-woocommerce:rw

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: somerootpassword
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  test:
    build:
      dockerfile: Dockerfile
      context: .
      target: test
      args:
        PHP_VERSION: $PHP_VERSION
        THECODINGMACHINE_VERSION: $THECODINGMACHINE_VERSION
        BUILD_THECODINGMACHINE_VERSION: $BUILD_THECODINGMACHINE_VERSION
        WORDPRESS_VERSION: $WORDPRESS_VERSION
        WOOCOMMERCE_VERSION: $WOOCOMMERCE_VERSION
    environment:
      WORDPRESS_DB_HOST: db-test
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: examplepass
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ./mount/:/usr/src/app/mount/:rw
    depends_on:
      db-test:
        condition: service_healthy

  db-test:
    image: mysql:5.7
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: somerootpassword
    volumes:
      - db-test:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8881:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: somerootpassword

volumes:
  db:
  db-test:
  test-run:
