name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Install packages
        run: composer install --ignore-platform-reqs --prefer-dist --no-dev --optimize-autoloader

      - name: Apply version with build
        if: ${{ ! startsWith( 'refs/tags/', github.ref ) }}
        run: php dev-tools/set-version.php ${{ steps.previoustag.outputs.tag }}-b$GITHUB_RUN_ID storekeeper-woocommerce-b2c.php

      - name: Set release version
        if: ${{ startsWith( 'refs/tags/', github.ref ) }}
        run: php dev-tools/set-version.php ${{ steps.previoustag.outputs.tag }} storekeeper-woocommerce-b2c.php

      - name: Put all in directory
        run: |
          mkdir storekeeper-woocommerce-b2c
          ls -a | grep -v  '^storekeeper-woocommerce-b2c$' | xargs mv -t  storekeeper-woocommerce-b2c

      - uses: actions/upload-artifact@v2
        with:
          name: storekeeper-woocommerce-b2c
          if-no-files-found: error
          # wildcard on the first line is needed to preserve the structure, actions/upload-artifact quirk
          path: |
            storekeeper-woocommerce-*/exports/**
            storekeeper-woocommerce-b2c/i18n/**
            storekeeper-woocommerce-b2c/scripts/**
            storekeeper-woocommerce-b2c/src/**
            storekeeper-woocommerce-b2c/vendor/**
            storekeeper-woocommerce-b2c/composer*
            storekeeper-woocommerce-b2c/*.php
            storekeeper-woocommerce-b2c/Readme.txt

      - name: Release
        uses: ncipollo/release-action@v1
        if: ${{ startsWith( 'refs/tags/', github.ref ) }}
        with:
          artifacts: "storekeeper-woocommerce-b2c"
          token: ${{ secrets.GITHUB_TOKEN }}
