name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Install packages
        run: composer install --ignore-platform-reqs --prefer-dist --no-dev --optimize-autoloader

      - name: Apply version
        run: php dev-tools/add-build-to-version.php $GITHUB_RUN_ID storekeeper-woocommerce-b2c.php

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'storekeeper-woocommerce-b2c.zip'
          exclusions: '*.git* /tests/* /*docker* /*docs/* /*Docker* phpunit.xml Makefile /.php* /.env*'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "storekeeper-woocommerce-b2c.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease:  ${{ ! startsWith( 'refs/tags/', github.ref ) }}
