name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'storekeeper-woocommerce-b2c'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Install packages
        run: cd storekeeper-woocommerce-b2c && composer install --ignore-platform-reqs --prefer-dist --no-dev --optimize-autoloader

      - name: Apply version
        run: php storekeeper-woocommerce-b2c/dev-tools/add-build-to-version.php $GITHUB_RUN_ID storekeeper-woocommerce-b2c/storekeeper-woocommerce-b2c.php

      - uses: actions/upload-artifact@v2
        with:
          name: storekeeper-woocommerce-b2c
          if-no-files-found: error
          # wildcard on the first line is needed to preserve the structure, actions/upload-artifact quirk
          path: |
            storekeeper-woocommerce-*/exports/**
            storekeeper-woocommerce-b2c/i18n/**
            storekeeper-woocommerce-b2c/scripts/**
            storekeeper-woocommerce-b2c/src/**
            storekeeper-woocommerce-b2c/composer*
            storekeeper-woocommerce-b2c/*.php
            storekeeper-woocommerce-b2c/Readme.txt
