name: Create Archive
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: version
        run: |
          LAST_VERSION_TAG=`git describe --tags --abbrev=0 --exclude=latest`
          echo ::set-output name=LAST_VERSION::${LAST_VERSION}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          tools: composer
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Install packages
        run: composer install --ignore-platform-reqs --prefer-dist --no-dev --optimize-autoloader

      - name: Apply version with build
        if: ${{ ! startsWith( github.ref, 'refs/tags/' ) }}
        run: php dev-tools/set-version.php ${{ steps.version.outputs.LAST_VERSION }}-b$GITHUB_RUN_ID storekeeper-woocommerce-b2c.php

      - name: Set release version
        if: ${{ startsWith( github.ref, 'refs/tags/' ) }}
        run: php dev-tools/set-version.php ${{ steps.version.outputs.LAST_VERSION }} storekeeper-woocommerce-b2c.php

      - name: Create zip
        run: |
          mkdir storekeeper-woocommerce-b2c
          ls -a | grep -v  '^storekeeper-woocommerce-b2c$' | grep -v '^\.*$' | xargs mv -t  storekeeper-woocommerce-b2c
          zip -r storekeeper-woocommerce-b2c.zip \
            storekeeper-woocommerce-b2c/exports \
            storekeeper-woocommerce-b2c/i18n \
            storekeeper-woocommerce-b2c/scripts\
            storekeeper-woocommerce-b2c/vendor \
            storekeeper-woocommerce-b2c/composer* \
            storekeeper-woocommerce-b2c/*.php \
            storekeeper-woocommerce-b2c/Readme.txt

      - uses: actions/upload-artifact@v2
        with:
          name: storekeeper-woocommerce-b2c
          if-no-files-found: error
          path: |
            storekeeper-woocommerce-b2c.zip

      - name: Release latest
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          prerelease: true
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            storekeeper-woocommerce-b2c.zip

      - name: Release version
        uses: marvinpinto/action-automatic-releases@v1.2.0
        if: ${{ startsWith( github.ref, 'refs/tags/' ) }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            storekeeper-woocommerce-b2c.zip
