# based on https://github.com/woocommerce/woocommerce/blob/trunk/.github/workflows/pr-unit-tests.yml
name: Run unit tests on PR
on:
  push
jobs:
  test:
    name: PHP ${{ matrix.php }} WP ${{ matrix.wp }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.3' ]
        wp: [ "latest" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test
