name: Release version
on:
  push:
    tags:
      - "*"
jobs:
  release-version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: storekeeper-woocommerce-b2c

      - name: Release
        uses: "marvinpinto/action-automatic-releases@1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            storekeeper-woocommerce-b2c.zip
