name: Set latest version on

on:
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Latest Release Tag
        id: latest_release
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          echo "::set-output name=tag::$LATEST_TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if Current Release is Latest
        id: check_latest
        run: | 
          if [ "${{ github.event.release.tag_name }}" == "${{ steps.latest_release.outputs.tag }}" ]; then
            echo "::set-output name=is_latest::true"
          else
            echo "::set-output name=is_latest::false"
            echo "This is not the latest release. Skipping upload."
          fi

      - name: Create Latest File
#        if: steps.check_latest.outputs.is_latest == 'true'
        run: echo ${{ steps.latest_release.outputs.tag }} > LATEST

      - name: Upload to FTP
#        if: steps.check_latest.outputs.is_latest == 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.VERSION_FTP_SERVER }}
          username: ${{ secrets.VERSION_FTP_USERNAME }}
          password: ${{ secrets.VERSION_FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./
