name: Set latest version on

on:
  release:
    types: [published, edited]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Tag
        id: latest_release
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          echo "TAG=$LATEST_TAG" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if Current Release is Latest
        id: check_latest
        run: |
          if [ "${{ github.event.release.tag_name }}" == "$TAG" ]; then
            echo "IS_LATEST=1" >> $GITHUB_ENV
            echo $TAG > LATEST
            echo "Latest release:"
            cat LATEST
          else
            echo "IS_LATEST=0" >> $GITHUB_ENV
            echo "This (=${{ github.event.release.tag_name }}) is not the latest release (=$TAG). Skipping upload."
          fi

      - name: Upload to FTP
#        if: env.IS_LATEST == '1'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.VERSION_FTP_SERVER }}
          username: ${{ secrets.VERSION_FTP_USERNAME }}
          password: ${{ secrets.VERSION_FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./
